[package]
name = "dapptools"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
ethers = "0.4.0"
eyre = "0.6.5"
tokio = { version = "1.10.1", features = ["macros"] }
rustc-hex = "2.1.0"
serde_json = "1.0.67"
